// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type FinancialAccount struct {
	ID                     uuid.UUID
	UserID                 uuid.NullUUID
	FinancialAccountTypeID uuid.NullUUID
	Name                   string
	Balance                string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type FinancialAccountType struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transaction struct {
	ID                    uuid.UUID
	UserID                uuid.NullUUID
	TransactionTypeID     uuid.NullUUID
	FinancialAccountID    uuid.NullUUID
	TransactionCategoryID uuid.NullUUID
	Description           string
	Amount                string
	Note                  sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type TransactionCategory struct {
	ID                          uuid.UUID
	TransactionTypeID           uuid.NullUUID
	TransactionClassificationID uuid.NullUUID
	Name                        string
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}

type TransactionClassification struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TransactionType struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Username  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Password  string
}
